debug 1

diff --git a/.github/workflows/smoke.yml b/.github/workflows/smoke.yml
--- a/.github/workflows/smoke.yml
+++ b/.github/workflows/smoke.yml
@@ -43,13 +43,13 @@ jobs:
           pip install -r requirements-build.txt
           pip install -r requirements.txt
 
-      - name: Set Ollama model to be used for related test case
-        shell: bash
-        run: |
-          build_scripts/set_ollama_model.sh
+      # - name: Set Ollama model to be used for related test case
+      #   shell: bash
+      #   run: |
+      #     build_scripts/set_ollama_model.sh
       
-      - name: Show installed packages
-        run: pip freeze
+      # - name: Show installed packages
+      #   run: pip freeze
 
       - name: Set up AWS config & credentials
         env:
@@ -65,7 +65,7 @@ jobs:
           output=json
 
           [profile daiDev]
-          role_arn=arn:aws:iam::111111:role/testonly
+          role_arn=arn:aws:iam::613076437200:role/LeafDev
           region=us-west-2
           source_profile=default
           EOF
@@ -87,29 +87,32 @@ jobs:
           cat ~/.aws/config
           echo "--- ~/.aws/credentials ---"
           cat ~/.aws/credentials
+      
+      - name: List Bedrock foundation models
+        run: aws bedrock list-foundation-models --profile daiDev
 
-      - name: Start server & run smoke tests & print server-log if any failure
-        shell: bash
-        env:
-          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
-          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
-          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
-          AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
-          OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
-          AGENT_TOOL_PATH: "./neuro_san/coded_tools"
-          PYTHONPATH: ${{ env.PYTHONPATH }}:.
-        run: |
-          build_scripts/server_start.sh
+      # - name: Start server & run smoke tests & print server-log if any failure
+      #   shell: bash
+      #   env:
+      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+      #     ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
+      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
+      #     AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
+      #     AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
+      #     OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
+      #     AGENT_TOOL_PATH: "./neuro_san/coded_tools"
+      #     PYTHONPATH: ${{ env.PYTHONPATH }}:.
+      #   run: |
+      #     build_scripts/server_start.sh
 
-          if ! pytest -s --verbose -m "smoke" --timer-top-n 100 -n auto; then
-            echo "===================================================="
-            echo "===================================================="
-            echo "=== Server_Sevice_Agent.LOG ==="
-            cat agent.log || echo "(no agent.log found)"
-            echo "===================================================="
-            exit 1
-          fi
+      #     if ! pytest -s --verbose -m "smoke" --timer-top-n 100 -n auto; then
+      #       echo "===================================================="
+      #       echo "===================================================="
+      #       echo "=== Server_Sevice_Agent.LOG ==="
+      #       cat agent.log || echo "(no agent.log found)"
+      #       echo "===================================================="
+      #       exit 1
+      #     fi
 
       - name: Notify Slack on success
         if: success()
